spring:
  redis:
    database: 1
    host: 152.136.81.61
    port: 6379
    timeout: 3000ms
  datasource:
    url: jdbc:mysql://152.136.81.61:3306/store?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=FALSE
   # url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=FALSE
   # url: jdbc:mysql://152.136.81.61:3306/store?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=FALSE
    username: root
   # password: 211314wang
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mystore-client-provider
  zipkin:
    sender:
      type: web
    base-url: http://152.136.81.61:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://152.136.81.61:18080/eureka/
server:
  port: 18881
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: club.mystore.pojo
#logging:
 # level:
 #   root: info
