server:
  port: 11111
spring:
  redis:
    database: 1
    host: 152.136.81.61
    port: 6379
    timeout: 3000ms
eureka:
  client:
    service-url:
      defaultZone: http://152.136.81.61:18080/eureka/
#ribbon:
#  ReadTimeout: 60000  # 单位毫秒数
#  SocketTimeout: 60000
zuul:
  routes:
    mystore-client-consumer:
      #service-id: mystore-client-consumer
      path: /client/**
      url: http://118.25.27.220:18081
#zuul:
#  host:
#    socket-timeout-millis: 60000
#    connect-timeout-millis: 60000  
#  routes:
#    mystore-client-consumer: /client/**
# /userlogin -> /user/userlogin
#    dm-xxxx-consumer: /xxxx/**
#      关闭某个过滤器,写类名字
#  SecondFilter:
#    pre:
#      disable: true
