spring:
  redis:
    database: 1
    host: 119.45.52.153
    port: 6379
    timeout: 3000ms
  datasource:
   # url: jdbc:mysql://152.136.81.61:3306/computer?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=FALSE
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=FALSE
   # url: jdbc:mysql://152.136.81.61:3306/store?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=FALSE
    username: root
   # password: 211314wang
    password: 211314wcc
    driver-class-name: com.mysql.cj.jdbc.Driver
# application:
#    name: mystore-client-provider
  zipkin:
    sender:
      type: web
    base-url: http://119.45.52.153:9411
  sleuth:
    sampler:
      probability: 1

eureka:
#  instance:
#    ip-address: 119.3.28.119
#    prefer-ip-address: true
#    instance-id: 119.3.28.119:${server.port}
  client:
    service-url:
      defaultZone: http://119.45.52.153:18080/eureka/
server:
  port: 18881
mybatis:
  mapper-locations: classpath:mapper/blog/*Mapper.xml
  type-aliases-package: club.cm.blog.enty
#logging:
 # level:
 #   root: info
